name: Update MiLB Season Team Pitching Stats
on:
  schedule:
    - cron: "10 0 * 4-9 *"
    - cron: "10 0 * 1,2,10-12 *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas
          python -m pip install pyarrow
          python -m pip install requests
          python -m pip install tqdm
          python -m pip install bs4
          python -m pip install lxml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run Python Script
        run: |
          python get_milb_team_season_stats.py --season 2025 --level aaa --stat_type pitching
          python get_milb_team_season_stats.py --season 2025 --level aa --stat_type pitching
          python get_milb_team_season_stats.py --season 2025 --level a+ --stat_type pitching
          python get_milb_team_season_stats.py --season 2025 --level a --stat_type pitching
          python get_milb_team_season_stats.py --season 2025 --level rk --stat_type pitching

      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "season_stats/team/*.csv"
          branches: "main"
          # update_latest_release: true
          overwrite: true
          verbose: true
          default_release_name: "MiLB_Season_Team_Pitching"
